/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import object.Karyawan;
import service.DigitalClockService;
import service.I18nService;
import service.KaryawanService;
import service.LogAbsensiService;
import service.SerialService;
import utill.EncryptionUtils;
import utill.SecurityUtils;

/**
 *
 * @author ASUS
 */
public class AttendancePage extends javax.swing.JFrame implements service.I18nService.I18nChangeListener {

        // Referensi thread disimpan untuk ditrack jika dibutuhkan (misal: untuk
        // stop/cek status)
        private Thread clockThread;

        Thread delayThread;

        /**
         * Creates new form AttendancePage
         */
        public AttendancePage() {
                initComponents();
                applyTheme();
                initClock(jLabel2);
                updateStatusLabel();

                // inisialisasi thread delayThread
                updateLabelWithDelay(jLabel8, "");
                setupAttendanceWorkflow();
                service.I18nService.registerListener(this);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(104, 23, 39));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Jumat, 5 Juni 2026, 12:12:12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Silahkan Tap Kartu Anda");

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nama Lengkap:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID Karyawan:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jabatan: ");

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Avatar");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(153, 51, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("jLabel8");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String mockUid = jTextField1.getText();
        SerialService.getInstance().simulateBroadcast(mockUid);
    
    }//GEN-LAST:event_jTextField1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                
        System.setProperty("KEY", "CafeAbsensi1234"); // 
    java.awt.EventQueue.invokeLater(() -> {
        new AttendancePage().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
        private void initClock(JLabel lblJam) {
        DigitalClockService service = new DigitalClockService(lblJam, "EEEE, d MMMM yyyy, HH:mm:ss");

        // 1. Ambil objek thread dari service
        clockThread = service.getThread();

        // 2. Beri nama secara mandiri untuk debugging/tracking
        clockThread.setName("Thread-Jam-Kiosk");

        // 3. Atur daemon secara mandiri sebelum start [Conversation History]
        clockThread.setDaemon(true);

        // 4. Jalankan thread (Fase New -> Runnable) [3]
        clockThread.start();

        System.out.println("Memulai: " + clockThread.getName() + " (Daemon: " + clockThread.isDaemon() + ")");
    }

    private void setupAttendanceWorkflow() {
        KaryawanService krService = new KaryawanService();
        LogAbsensiService logService = new LogAbsensiService();

        // Mendaftarkan handler asinkron ke SerialService [11]
        SerialService.getInstance().addHandler(dataRfid -> {
            // 1. HASH: Mengamankan UID menggunakan SHA-256 [12, 13]
            String hashedUid = SecurityUtils.getHash(dataRfid, SecurityUtils.SHA_256);

            // 2. MATCH: Mencari data karyawan di database
            Karyawan k = krService.findByUid(hashedUid);
            boolean isSuccess = (k != null);

            // 3. SAVE: Mencatat log absensi [6]
            logService.simpanLog(hashedUid, Settings.prefs.get("LAST_STATUS", Settings.statusAbsen));

            // 4. NOTIFY: Update GUI secara aman (mencegah UI Freezing) [10]
            SwingUtilities.invokeLater(() -> {
                if (isSuccess) {
                    // Update Card UI dengan data dari objek Karyawan [14, 15]
                    if (k != null) {
                    jLabel4.setText(service.I18nService.get("attendance.nama") + " " + k.getNamaLengkap());

                    String rawId = k.getIdKaryawan();
                    String idKaryawan;
                    if (rawId == null || rawId.isEmpty()) {
                        idKaryawan = "(belum diisi)";
                    } else {
                        idKaryawan = EncryptionUtils.decrypt(rawId);
                        if (idKaryawan == null) idKaryawan = "(gagal decrypt)";
                    }
                    jLabel5.setText(service.I18nService.get("attendance.id") + " " + idKaryawan);
                    jLabel6.setText(service.I18nService.get("attendance.jabatan") + " " + service.I18nService.get("jabatan." + k.getJabatan().toLowerCase()));
                    updateLabelWithDelay(jLabel8, service.I18nService.get("attendance.accepted"));
}
                }
            });
        });
    }

    private void updateLabelWithDelay(JLabel comp, String info) {

    if (delayThread != null && delayThread.isAlive()) {
        delayThread.interrupt();
    }

    delayThread = new Thread(() -> {

        comp.setText(info);

        try {

            for (int i = 3; i >= 1; i--) {
                Thread.sleep(1000);
            }

            SwingUtilities.invokeLater(() -> {

                String status = Settings.prefs.get("LAST_STATUS", "Masuk");

                if (status.equals("Masuk")) {
                    comp.setText(I18nService.get("status.masuk"));
                } else {
                    comp.setText(I18nService.get("status.pulang"));
                }

            });

        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    });

    delayThread.setName("delayThread");
    delayThread.setDaemon(true);
    delayThread.start();
}
    private void applyTheme() {
    // Header jam
    jPanel2.setBackground(new java.awt.Color(44, 28, 14));
    jPanel2.setLayout(new java.awt.BorderLayout());
    jLabel2.setForeground(new java.awt.Color(255, 183, 77));
    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

    
    // Label tap kartu
    jLabel3.setText(service.I18nService.get("attendance.tap"));
    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22));
    jLabel3.setForeground(new java.awt.Color(255, 220, 150));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    // TextField RFID
    jTextField1.setBackground(new java.awt.Color(50, 35, 20));
    jTextField1.setForeground(new java.awt.Color(255, 220, 150));
    jTextField1.setCaretColor(new java.awt.Color(255, 183, 77));
    jTextField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 183, 77), 2, true),
        javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)
    ));
    jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14));
    
    jTextField1.setMaximumSize(new java.awt.Dimension(300, 40));
    jTextField1.setPreferredSize(new java.awt.Dimension(300, 40));

    // Card info karyawan
    jPanel7.setBackground(new java.awt.Color(62, 38, 18));
    jPanel7.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 183, 77), 2, true),
        javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)
        
    ));
    
    jPanel7.setMaximumSize(new java.awt.Dimension(600, 120));
jPanel7.setPreferredSize(new java.awt.Dimension(600, 120));

    // Avatar
    jLabel7.setBackground(new java.awt.Color(139, 90, 43));
    jLabel7.setForeground(new java.awt.Color(255, 220, 150));
    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12));

    // Label info karyawan
    // Label info karyawan
    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13));
    jLabel4.setForeground(new java.awt.Color(255, 220, 150));
    jLabel4.setText(service.I18nService.get("attendance.nama"));

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13));
    jLabel5.setForeground(new java.awt.Color(255, 220, 150));
    jLabel5.setText(service.I18nService.get("attendance.id"));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13));
    jLabel6.setForeground(new java.awt.Color(255, 220, 150));
    jLabel6.setText(service.I18nService.get("attendance.jabatan"));

    // Status bar
    jLabel8.setBackground(new java.awt.Color(139, 90, 43));
    jLabel8.setForeground(java.awt.Color.WHITE);
    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14));

    // Rebuild layout
    getContentPane().removeAll();
    getContentPane().setLayout(new java.awt.BorderLayout());
    getContentPane().setBackground(new java.awt.Color(30, 18, 8));
    getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

    // Content panel tengah
    javax.swing.JPanel contentPanel = new javax.swing.JPanel();
    contentPanel.setBackground(new java.awt.Color(30, 18, 8));
    contentPanel.setLayout(new java.awt.GridBagLayout());

    // Inner panel berisi semua konten
    javax.swing.JPanel innerPanel = new javax.swing.JPanel();
    innerPanel.setBackground(new java.awt.Color(30, 18, 8));
    innerPanel.setLayout(new javax.swing.BoxLayout(innerPanel, javax.swing.BoxLayout.Y_AXIS));
    innerPanel.setPreferredSize(new java.awt.Dimension(700, 400));

    jLabel3.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    jTextField1.setMaximumSize(new java.awt.Dimension(600, 40));
    jTextField1.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    jPanel7.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    jLabel8.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
    jLabel8.setMaximumSize(new java.awt.Dimension(600, 35));

    innerPanel.add(javax.swing.Box.createVerticalStrut(30));
    innerPanel.add(jLabel3);
    innerPanel.add(javax.swing.Box.createVerticalStrut(15));
    innerPanel.add(jTextField1);
    innerPanel.add(javax.swing.Box.createVerticalStrut(20));
    innerPanel.add(jPanel7);
    innerPanel.add(javax.swing.Box.createVerticalStrut(5));
    innerPanel.add(jLabel8);

    contentPanel.add(innerPanel);
    getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

    revalidate();
    repaint(); 
}
    
    
    
private void updateStatusLabel() {

    String status = Settings.prefs.get("LAST_STATUS", "Masuk");

    if (status.equals("Masuk")) {
        jLabel8.setText(service.I18nService.get("status.masuk"));
    } else {
        jLabel8.setText(service.I18nService.get("status.pulang"));
    }
}
    @Override
public void onLanguageChanged() {
    
    SwingUtilities.invokeLater(() -> {
        applyTheme();
        updateStatusLabel();

        revalidate();
        repaint();
    });
}
    
    

}
