/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author ASUS
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        
        buildDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

private void buildDashboard() {

    removeAll();
    setLayout(new java.awt.BorderLayout());

    javax.swing.JPanel main = new javax.swing.JPanel();
    main.setBackground(java.awt.Color.WHITE);
    main.setLayout(new java.awt.GridLayout(2, 2, 20, 20));
    main.setBorder(javax.swing.BorderFactory.createEmptyBorder(20,20,20,20));

    main.add(createCard("Total Karyawan", "120"));
    main.add(createCard("Hadir Hari Ini", "98"));
    main.add(createCard("Tanggal", java.time.LocalDate.now().toString()));
    main.add(createCard("Jam", java.time.LocalTime.now().toString()));

    add(main, java.awt.BorderLayout.CENTER);

    revalidate();
    repaint();
}

private javax.swing.JPanel createCard(String title, String value){

    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setBackground(new java.awt.Color(245,245,245));
    card.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.LIGHT_GRAY));
    card.setLayout(new java.awt.BorderLayout());

    javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
    lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTitle.setFont(new java.awt.Font("Segoe UI",1,16));

    javax.swing.JLabel lblValue = new javax.swing.JLabel(value);
    lblValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblValue.setFont(new java.awt.Font("Segoe UI",1,28));

    card.add(lblTitle, java.awt.BorderLayout.NORTH);
    card.add(lblValue, java.awt.BorderLayout.CENTER);

    return card;
}


}
