/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import object.Karyawan;
import service.KaryawanService;
import utill.EncryptionUtils;
import utill.SecurityUtils;

/**
 *
 * @author ASUS
 */
public class KaryawanPanel extends javax.swing.JPanel implements service.I18nService.I18nChangeListener {
    
    

    /**
     * Creates new form admin_page
     */
    public KaryawanPanel() {
        initComponents();
       
        loadSearchIcon();
        customStyle();
        
        // Style labels
jLabel1.setForeground(new java.awt.Color(255, 220, 150));
jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13));
jLabel2.setForeground(new java.awt.Color(255, 220, 150));
jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13));
jLabel3.setForeground(new java.awt.Color(255, 220, 150));
jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13));
jLabel4.setForeground(new java.awt.Color(255, 220, 150));
jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13));

// Style panel atas
jPanel3.setBackground(new java.awt.Color(74, 44, 18));
jPanel5.setBackground(new java.awt.Color(74, 44, 18));

// Style panel bawah (card area)
jPanel4.setBackground(new java.awt.Color(62, 38, 18));

// Apply i18n
applyI18n();

// Register listener
service.I18nService.registerListener(this);
        
        setBackground(new java.awt.Color(60, 40, 15)); // coklat tua

    jPanel1.setBackground(new java.awt.Color(235, 235, 235)); 
    jPanel2.setBackground(new java.awt.Color(106, 80, 20));   
    
    txtCari.setText(service.I18nService.get("karyawan.cari"));
txtCari.setForeground(Color.GRAY);
    txtCari.setBackground(new java.awt.Color(255, 248, 220)); // cream
txtCari.setForeground(new java.awt.Color(60, 60, 60));
txtCari.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 140, 70)),
        javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8)
        
        
));
        showData("");
    }
    
    private void loadSearchIcon() {

    ImageIcon icon = new ImageIcon(
            getClass().getResource("/images/icon-search.png")
    );

    Image img = icon.getImage().getScaledInstance(
            18,
            18,
            Image.SCALE_SMOOTH
    );

    lblSearchIcon.setIcon(new ImageIcon(img));
    lblSearchIcon.setText("");
}
    
    
        private void customStyle() {

        jPanel1.setBackground(new java.awt.Color(74,44,18));
        jPanel2.setBackground(new java.awt.Color(94,70,21));

        btnSave.setBackground(new java.awt.Color(212,175,55));
        btnSave.setForeground(java.awt.Color.BLACK);
        btnSave.setFocusPainted(false);

        btnUpdate.setBackground(new java.awt.Color(212,175,55));
        btnUpdate.setForeground(java.awt.Color.BLACK);
        btnUpdate.setFocusPainted(false);

        btnRefresh.setBackground(new java.awt.Color(139,90,43));
        btnRefresh.setForeground(java.awt.Color.WHITE);
        btnRefresh.setFocusPainted(false);

        txtUID.setBackground(new java.awt.Color(255,248,220));
        txtKRID.setBackground(new java.awt.Color(255,248,220));
        txtKRName.setBackground(new java.awt.Color(255,248,220));

        txtKRJabt.setBackground(new java.awt.Color(255,248,220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        txtKRName = new javax.swing.JTextField();
        txtKRID = new javax.swing.JTextField();
        txtKRJabt = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtCari = new javax.swing.JTextField();
        lblSearchIcon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(30, 18, 8));

        jLabel1.setText("Jabatan");

        jLabel2.setText("UID");

        jLabel3.setText("ID Karyawan");

        jLabel4.setText("Nama Karyawan");

        txtKRJabt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barista", "Admin", "Waiters", "Manager", "Chef", "Cashier", " " }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 36));

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCari.setPreferredSize(new java.awt.Dimension(250, 28));
        txtCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCariFocusLost(evt);
            }
        });
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        lblSearchIcon.setPreferredSize(new java.awt.Dimension(28, 28));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtKRID))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKRName)
                    .addComponent(txtKRJabt, 0, 143, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKRName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(txtKRID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKRJabt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh))
                        .addGap(83, 83, 83))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(30, 18, 8));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String encryptedId = EncryptionUtils.encrypt(txtKRID.getText());
        if (encryptedId == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal enkripsi ID! Cek VM Options -DKEY");
            return;
        }

        Karyawan K = new Karyawan();
        K.setUidRfid(SecurityUtils.getHash(txtUID.getText(), SecurityUtils.SHA_256));
        K.setIdKaryawan(encryptedId);
        K.setNamaLengkap(txtKRName.getText());
        K.setJabatan(txtKRJabt.getSelectedItem().toString());
        KaryawanService service = new KaryawanService();
        service.tambahKaryawan(K);
        showData("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         Karyawan K = new Karyawan();
    K.setUidRfid(SecurityUtils.getHash(txtUID.getText(), SecurityUtils.SHA_256));
    K.setIdKaryawan(txtKRID.getText()); // langsung pakai, sudah terenkripsi dari card
    K.setNamaLengkap(txtKRName.getText());
    K.setJabatan(txtKRJabt.getSelectedItem().toString());
    KaryawanService service = new KaryawanService();
    service.updateKaryawan(K);
    refresAll();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresAll();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        showData(txtCari.getText());
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusGained
        // TODO add your handling code here:
        
        if(txtCari.getText().equals(service.I18nService.get("karyawan.cari"))){
    txtCari.setText("");
}
        txtCari.setForeground(Color.BLACK);
    
    }//GEN-LAST:event_txtCariFocusGained

    private void txtCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusLost
        // TODO add your handling code here:
        
        if (txtCari.getText().isEmpty()) {
        txtCari.setText(service.I18nService.get("karyawan.cari"));
        txtCari.setForeground(Color.GRAY);
    }
    }//GEN-LAST:event_txtCariFocusLost
    
        

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRefresh;
    public static javax.swing.JButton btnSave;
    public static javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblSearchIcon;
    public javax.swing.JTextField txtCari;
    public static javax.swing.JTextField txtKRID;
    public static javax.swing.JComboBox<String> txtKRJabt;
    public static javax.swing.JTextField txtKRName;
    public static javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables

    
    public static void showData(String key) {
            KaryawanService K = new KaryawanService();
            K.tampilKaryawan(jPanel4, key); 
        }
        
        private void refresAll() {
        showData("");
        txtUID.setText("");
        txtKRID.setText("");
        txtKRID.setEnabled(true);
        txtKRName.setText("");
        txtKRJabt.setSelectedIndex(0);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        txtUID.requestFocus();
    }
        
        private void applyI18n() {
    jLabel1.setText(service.I18nService.get("karyawan.jabatan"));
    jLabel2.setText(service.I18nService.get("karyawan.uid"));
    jLabel3.setText(service.I18nService.get("karyawan.id"));
    jLabel4.setText(service.I18nService.get("karyawan.nama"));
    btnSave.setText(service.I18nService.get("karyawan.save"));
    btnUpdate.setText(service.I18nService.get("karyawan.update"));
    btnRefresh.setText(service.I18nService.get("karyawan.refresh"));
    txtCari.setText(service.I18nService.get("karyawan.cari"));
    
    String selected = txtKRJabt.getSelectedItem() == null ?
        "" : txtKRJabt.getSelectedItem().toString();

txtKRJabt.removeAllItems();

txtKRJabt.addItem(service.I18nService.get("jabatan.barista"));
txtKRJabt.addItem(service.I18nService.get("jabatan.admin"));
txtKRJabt.addItem(service.I18nService.get("jabatan.waiters"));
txtKRJabt.addItem(service.I18nService.get("jabatan.manager"));
txtKRJabt.addItem(service.I18nService.get("jabatan.chef"));
txtKRJabt.addItem(service.I18nService.get("jabatan.cashier"));
}

@Override
public void onLanguageChanged() {
    javax.swing.SwingUtilities.invokeLater(() -> {
        applyI18n();
        revalidate();
        repaint();
    });
}
    
}
