/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.util.Locale;
import java.util.prefs.Preferences;
import javax.swing.JPanel;
import palette.SlidingLanguageToggle;
import service.I18nService;

/**
 *
 * @author ASUS
 */

public class Settings extends JPanel implements service.I18nService.I18nChangeListener {

    public static String statusAbsen = "Masuk";
    
    public static Preferences prefs = Preferences.userNodeForPackage(Settings.class);
    public static String statusLang = "id";
    private palette.SlidingLanguageToggle langToggle;

    public Settings() {
        I18nService.setLocale(Locale.of(prefs.get("LANGUAGE", "id")));
        initComponents();
        statusAbsen = prefs.get("LAST_STATUS", "Masuk");
        statusLang = prefs.get("LANGUAGE", "id");
        slidingStatusToggle1.setStatusByString(statusAbsen);
       
        I18nService.registerListener(this);
        langToggle = new SlidingLanguageToggle();
        langToggle.setSelectedLanguageIndexByString(statusLang);
    
        buildUI(); 

        
    }
    /**
     * Creates new form Settings
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        slidingStatusToggle1 = new palette.SlidingStatusToggle();

        slidingStatusToggle1.setText("slidingStatusToggle1");
        slidingStatusToggle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slidingStatusToggle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(slidingStatusToggle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(slidingStatusToggle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slidingStatusToggle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slidingStatusToggle1ActionPerformed
        // TODO add your handling code here:
        if (slidingStatusToggle1.isSelected()) {
            statusAbsen = "Pulang";
    } else {
            statusAbsen = "Masuk";
    }

    prefs.put("LAST_STATUS", statusAbsen);
    
    }//GEN-LAST:event_slidingStatusToggle1ActionPerformed

    

                             
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private palette.SlidingStatusToggle slidingStatusToggle1;
    // End of variables declaration//GEN-END:variables

    private void buildUI() {
    setLayout(new java.awt.BorderLayout());
    setBackground(new java.awt.Color(245, 235, 220));

    javax.swing.JLabel lblTitle = new javax.swing.JLabel(service.I18nService.get("sidebar.settings"));
    lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22));
    lblTitle.setForeground(new java.awt.Color(62, 38, 18));
    lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 10, 0));
    add(lblTitle, java.awt.BorderLayout.PAGE_START);

    javax.swing.JPanel mainPanel = new javax.swing.JPanel();
    mainPanel.setBackground(new java.awt.Color(245, 235, 220));
    mainPanel.setLayout(new java.awt.GridLayout(2, 1, 20, 20));
    mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

    // Card Status
    javax.swing.JPanel cardStatus = new javax.swing.JPanel(new java.awt.BorderLayout());
    cardStatus.setBackground(new java.awt.Color(62, 38, 18));
    cardStatus.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 183, 77), 2, true),
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));
    javax.swing.JLabel lblStatus = new javax.swing.JLabel(service.I18nService.get("attendance.status"));
    lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 16));
    lblStatus.setForeground(new java.awt.Color(255, 183, 77));
    cardStatus.add(lblStatus, java.awt.BorderLayout.PAGE_START);

    // Wrapper tengah untuk toggle status
    javax.swing.JPanel statusWrapper = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 20));
    statusWrapper.setBackground(new java.awt.Color(62, 38, 18));
    slidingStatusToggle1.setPreferredSize(new java.awt.Dimension(350, 45));
    statusWrapper.add(slidingStatusToggle1);
    cardStatus.add(statusWrapper, java.awt.BorderLayout.CENTER);

    // Card Bahasa
    javax.swing.JPanel cardBahasa = new javax.swing.JPanel(new java.awt.BorderLayout());
    cardBahasa.setBackground(new java.awt.Color(62, 38, 18));
    cardBahasa.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 183, 77), 2, true),
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));
    javax.swing.JLabel lblBahasa = new javax.swing.JLabel(service.I18nService.get("settings.language"));
    lblBahasa.setFont(new java.awt.Font("Segoe UI", 1, 16));
    lblBahasa.setForeground(new java.awt.Color(255, 183, 77));
    cardBahasa.add(lblBahasa, java.awt.BorderLayout.PAGE_START);

    langToggle.setPreferredSize(new java.awt.Dimension(350, 45));
    javax.swing.JPanel langWrapper = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 20));
    langWrapper.setBackground(new java.awt.Color(62, 38, 18));
    langWrapper.add(langToggle);
    cardBahasa.add(langWrapper, java.awt.BorderLayout.CENTER);

    mainPanel.add(cardStatus);
    mainPanel.add(cardBahasa);
    add(mainPanel, java.awt.BorderLayout.CENTER);

    revalidate();
    repaint();
}

@Override
public void onLanguageChanged() {
    javax.swing.SwingUtilities.invokeLater(() -> {
        // Simpan state toggle sebelum rebuild
        boolean isSelected = slidingStatusToggle1.isSelected();
        removeAll();
        buildUI();
        // Restore state toggle
        slidingStatusToggle1.setSelected(isSelected);
        revalidate();
        repaint();
    });
}


}




